# -*- coding: utf-8 -*-
"""Voice Changer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VTJRy3YUSo9DNO3cemBdQW81KTVBspEK
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install librosa

import librosa
import soundfile as sf
from IPython.display import Audio, display

# Load your MP3 audio file
audio_path = "/content/drive/MyDrive/Colab Notebooks/Dataset/DSP Recording/Jerome.mp3"
y, sr = librosa.load(audio_path, sr=None)

# Pitch up the audio
semitones_to_pitch_up = 5
y_pitched_up = librosa.effects.pitch_shift(y, sr=sr, n_steps=semitones_to_pitch_up)

# Define paths for exporting to Google Drive as MP3
output_path_up = "/content/drive/MyDrive/Colab Notebooks/Dataset/DSP Recording/pitched_up_jerome.mp3"

# Export pitched audio to MP3 files
sf.write(output_path_up, y_pitched_up, sr)

# Play the pitched audio in the notebook using IPython.display
print("Playing original audio:")
display(Audio(audio_path))
print("Playing pitched-up audio:")
display(Audio(output_path_up))

# Load your MP3 audio file
audio_path = "/content/drive/MyDrive/Colab Notebooks/Dataset/DSP Recording/Selwyn.mp3"
y, sr = librosa.load(audio_path, sr=None)

# Pitch down the audio
semitones_to_pitch_down = -2
y_pitched_down = librosa.effects.pitch_shift(y, sr=sr, n_steps=semitones_to_pitch_down)

# Define paths for exporting to Google Drive as MP3
output_path_down = "/content/drive/MyDrive/Colab Notebooks/Dataset/DSP Recording/pitched_down_selwyn.mp3"

# Export pitched audio to MP3 files
sf.write(output_path_down, y_pitched_down, sr)

# Play the pitched audio in the notebook using IPython.display
print("Playing original audio:")
display(Audio(audio_path))
print("Playing pitched-down audio:")
display(Audio(output_path_down))

# Load your MP3 audio file
audio_path = "/content/drive/MyDrive/Colab Notebooks/Dataset/DSP Recording/Sam.mp3"
y, sr = librosa.load(audio_path, sr=None)

# Pitch down the audio
semitones_to_pitch_down = -5
y_pitched_down = librosa.effects.pitch_shift(y, sr=sr, n_steps=semitones_to_pitch_down)

# Define paths for exporting to Google Drive as MP3
output_path_down = "/content/drive/MyDrive/Colab Notebooks/Dataset/DSP Recording/pitched_down_sam.mp3"

# Export pitched audio to MP3 files
sf.write(output_path_down, y_pitched_down, sr)

# Play the pitched audio in the notebook using IPython.display
print("Playing original audio:")
display(Audio(audio_path))
print("Playing pitched-down audio:")
display(Audio(output_path_down))